- name: install and run ngnix
  hosts: web
  before: yes
  tasks:
  - name: install ngnix
    ansible.builtin.package:
     name: ngnix
     state: present
  - name: ngnix start
    ansible.builtin.service:
     name: ngnix
     state:started


